#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
REPO_DIR=$(CDPATH= cd -- "$SCRIPT_DIR/../.." && pwd)
cargo test --locked --manifest-path "$REPO_DIR/shared/build-provenance/Cargo.toml"

TEST_DIRECTORY=$(mktemp -d "${TMPDIR:-/tmp}/moqcast-build-provenance.XXXXXX")
cleanup() {
    rm -f "$TEST_DIRECTORY/generated.txt" "$TEST_DIRECTORY/package.txt"
    rmdir "$TEST_DIRECTORY"
}
trap cleanup EXIT

PACKAGE_VARIANT=linux-x86_64-ubuntu24.04-glibc2.39
BUILD_DATE=2026-09-29T00:00:00Z
BUILD_DISTRO_ID=ubuntu
BUILD_DISTRO_VERSION=24.04
GLIBC_VERSION=2.39
PIPEWIRE_VERSION=1.0.5
ALSA_VERSION=1.2.11
INTENDED_TARGETS=ubuntu-24.04,mint-22
source "$SCRIPT_DIR/build-info.sh"
cat >"$TEST_DIRECTORY/generated.txt" <<EOF
app_version=fixture
build_identity=$PACKAGE_VARIANT
source_identity=fixture-dirty
dependency_identity=fixture-vendor
target=x86_64-unknown-linux-gnu
EOF
write_build_info "$TEST_DIRECTORY/package.txt" "$TEST_DIRECTORY/generated.txt"
# Packaging preserves every generated byte rather than reconstructing identities.
head -n 5 "$TEST_DIRECTORY/package.txt" | cmp - "$TEST_DIRECTORY/generated.txt"
grep -Fxq 'source_identity=fixture-dirty' "$TEST_DIRECTORY/package.txt"
PACKAGE_VARIANT=another-package
if write_build_info "$TEST_DIRECTORY/package.txt" "$TEST_DIRECTORY/generated.txt"; then
    echo "Packaging accepted provenance from a different variant." >&2
    exit 1
fi
