[package]
name = "moq-cast-desktop"
version = "0.1.0"
edition = "2024"
rust-version = "1.95"
license = "MIT OR Apache-2.0"

[workspace]

[dependencies]
anyhow = "1"
eframe = { version = "0.36.1", default-features = false, features = ["accesskit", "default_fonts", "persistence", "wayland", "wgpu", "x11"] }
moq-native = { git = "https://github.com/moq-dev/moq.git", rev = "68cf64603f067f64bc02fe800464aa59710a258c", default-features = false, features = ["aws-lc-rs", "mdns", "quinn"] }
thiserror = "2"
tokio = { version = "1.53.1", features = ["rt-multi-thread", "sync", "time"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
url = "2"

[target.'cfg(target_os = "linux")'.dependencies]
moq-mux = { git = "https://github.com/moq-dev/moq.git", rev = "68cf64603f067f64bc02fe800464aa59710a258c" }
moq-video = { git = "https://github.com/moq-dev/moq.git", rev = "68cf64603f067f64bc02fe800464aa59710a258c", default-features = false, features = ["nvenc", "pipewire"] }

[dev-dependencies]
rustls = { version = "0.23", features = ["aws-lc-rs"] }
tokio = { version = "1.53.1", features = ["macros"] }
